// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns cell index 0..(N²-1) for the next Tier-1 forced cat placement, or -1.
int calculateNextMove({
  required List<int> state,
  required List<int> regions,
  required int gridSize,
}) => RustLib.instance.api.crateApiMeowdokuCalculateNextMove(
  state: state,
  regions: regions,
  gridSize: gridSize,
);
